version: '3.8'
services:
  esp32-server:
    image: 192.168.101.99/yyn/192.168.101.99/yyn/esp32-server:1.0
    container_name: esp32-server
    restart: always
    network_mode: "bridge"
    volumes:
      - /appdata/share/esp32-server/asr-models:/opt/xiaozhi-es32-server/asr-models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              device_ids: ['1']
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - HOSTNAME=192.168.101.243
    ports:
      - "18089:8000"
